# HybridOps Workflow Definition - Pedro Valerio Methodology
# Version: 1.0.0
# Last Updated: 2026-01-28

name: hybrid-ops-pv
version: "1.0"
description: |
  HybridOps workflow template implementing the Pedro Valerio methodology
  for human-agent collaboration in software development.

metadata:
  author: Pedro Valerio
  license: MIT
  repository: https://github.com/SynkraAI/aios-hybrid-ops-pedro-valerio
  documentation: ../docs/workflow-diagram.md

# Configuration
config:
  # Default delegation mode: autonomous | hybrid | human-led
  default_mode: hybrid

  # Require human approval for these task types
  require_human_approval:
    - architecture_decisions
    - security_changes
    - database_migrations
    - production_deployments

  # Agent can act autonomously for these
  autonomous_tasks:
    - code_formatting
    - test_execution
    - documentation_updates
    - dependency_updates

# Workflow Stages
stages:
  - id: planning
    name: Planning Stage
    description: Define objectives and analyze requirements
    participants:
      human:
        role: decision_maker
        responsibilities:
          - Define business objectives
          - Set constraints and boundaries
          - Approve final plan
      agent:
        role: analyst
        responsibilities:
          - Analyze requirements
          - Identify risks
          - Propose solutions
    checkpoints:
      - name: requirements_complete
        type: human_approval
        criteria: All requirements documented and validated
      - name: plan_approved
        type: human_approval
        criteria: Implementation plan reviewed and approved

  - id: design
    name: Design Stage
    description: Create and refine technical design
    participants:
      human:
        role: domain_expert
        responsibilities:
          - Provide context
          - Review designs
          - Make architectural decisions
      agent:
        role: designer
        responsibilities:
          - Generate design options
          - Document architecture
          - Create diagrams
    checkpoints:
      - name: design_review
        type: human_review
        criteria: Design meets requirements and standards
      - name: design_approved
        type: human_approval
        criteria: Final design signed off

  - id: implementation
    name: Implementation Stage
    description: Execute the implementation plan
    participants:
      human:
        role: reviewer
        responsibilities:
          - Code review
          - Provide feedback
          - Unblock agent
      agent:
        role: implementer
        responsibilities:
          - Write code
          - Write tests
          - Self-review
    checkpoints:
      - name: code_complete
        type: agent_report
        criteria: All tasks implemented
      - name: code_reviewed
        type: human_review
        criteria: Code meets quality standards
      - name: tests_passing
        type: automated
        criteria: All tests pass

  - id: quality_assurance
    name: Quality Assurance Stage
    description: Verify quality and prepare for release
    participants:
      human:
        role: approver
        responsibilities:
          - Define test criteria
          - Review test results
          - Final approval
      agent:
        role: tester
        responsibilities:
          - Execute tests
          - Generate reports
          - Fix issues
    checkpoints:
      - name: qa_complete
        type: automated
        criteria: All quality gates pass
      - name: release_approved
        type: human_approval
        criteria: Ready for production

# Transitions
transitions:
  - from: planning
    to: design
    condition: plan_approved

  - from: design
    to: implementation
    condition: design_approved

  - from: implementation
    to: quality_assurance
    condition: code_reviewed AND tests_passing

  - from: quality_assurance
    to: complete
    condition: release_approved

  # Rollback transitions
  - from: design
    to: planning
    condition: requirements_changed
    type: rollback

  - from: implementation
    to: design
    condition: design_issues_found
    type: rollback

  - from: quality_assurance
    to: implementation
    condition: qa_failed
    type: rollback

# Task Delegation Rules
delegation:
  # Criteria for autonomous execution
  autonomous_criteria:
    - task_type in config.autonomous_tasks
    - risk_level == "low"
    - no_human_dependencies

  # Criteria for hybrid execution
  hybrid_criteria:
    - task_type not in config.require_human_approval
    - risk_level in ["low", "medium"]

  # Criteria for human-led execution
  human_led_criteria:
    - task_type in config.require_human_approval
    - risk_level == "high"
    - critical_path == true

# Integration with AIOS
aios_integration:
  agents:
    - agent: dev
      stages: [implementation]
      role: implementer

    - agent: qa
      stages: [quality_assurance]
      role: tester

    - agent: architect
      stages: [planning, design]
      role: analyst

    - agent: pm
      stages: [planning, quality_assurance]
      role: coordinator

  quality_gates:
    layer1:
      stage: implementation
      automated: true

    layer2:
      stage: quality_assurance
      human_review: true

    layer3:
      stage: quality_assurance
      human_approval: true

# Notifications
notifications:
  channels:
    - type: slack
      events: [stage_complete, approval_needed, blocked]

    - type: email
      events: [release_approved, rollback_triggered]

    - type: github
      events: [pr_created, pr_merged]

# Metrics
metrics:
  track:
    - cycle_time_per_stage
    - delegation_ratio
    - approval_turnaround_time
    - rollback_frequency
    - agent_autonomy_score

  thresholds:
    approval_turnaround: 4h
    stage_cycle_time: 24h
    agent_autonomy_target: 0.6

# Templates
templates:
  planning_document: |
    ## Objectives
    {{ objectives }}

    ## Requirements
    {{ requirements }}

    ## Constraints
    {{ constraints }}

    ## Proposed Approach
    {{ approach }}

  handoff_context: |
    ## Current State
    {{ current_state }}

    ## Completed Work
    {{ completed }}

    ## Pending Items
    {{ pending }}

    ## Blockers
    {{ blockers }}

# Exports
exports:
  - stages
  - transitions
  - delegation
  - aios_integration
